config/routes.rb
Headbook::Application.routes.draw do
  devise_for :users

  resources :posts

  resources :friendships

  resources :users

  root :to => 'static#frontpage'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  match "users/:id/adminify" => "users#adminify", :as => "make_admin"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :first_person_id, :second_person_id
  
  belongs_to :first_person, class_name: "User"
  belongs_to :second_person, class_name: "User"
  
  validates :first_person_id, presence: true
  validates :second_person_id, presence: true
  
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  #before_filter :signed_in_user
  before_filter :authenticate_user!
  respond_to :html, :js



  def create
    @user = User.find(params[:other_person_id])
    Friendship.create(:first_person_id => current_user.id, :second_person_id => @user.id)
    respond_with @user
  end

  def destroy

    @user = User.find(params[:other_person_id])
    @friendship = Friendship.find_by_first_person_id_and_second_person_id(current_user.id, @user.id) || 
    Friendship.find_by_first_person_id_and_second_person_id(@user.id, current_user.id)
    @friendship.destroy
    respond_with @user
  end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_person %><br />
    <%= f.number_field :first_person %>
  </div>
  <div class="field">
    <%= f.label :second_person %><br />
    <%= f.number_field :second_person %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <tr>
    <th>First person</th>
    <th>Second person</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendships.each do |friendship| %>
  <tr>
    <td><%= friendship.first_person %></td>
    <td><%= friendship.second_person %></td>
    <td><%= link_to 'Show', friendship %></td>
    <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
    <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First person:</b>
  <%= @friendship.first_person %>
</p>

<p>
  <b>Second person:</b>
  <%= @friendship.second_person %>
</p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>