config/routes.rb
Headbook::Application.routes.draw do
  devise_for :users

  resources :posts

  resources :friendships

  resources :users

  root :to => 'static#frontpage'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  match "users/:id/adminify" => "users#adminify", :as => "make_admin"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content,:user_id, :image
  belongs_to :user

  validates :user_id, :presence => true
  validates :content, :presence => true, :length => { :minimum => 1}
  # substitute ASC with DESC if we want a descending order
  default_scope order: 'posts.created_at DESC'

  has_attached_file :image, 
  	:storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :styles => { :medium => "600x400>", :thumb => "200x150>" },
    :dropbox_options => {
      :path => proc { |style| "/HeadBook/#{Rails.env}/#{style}/#{id}_#{image.original_filename}" }     
    }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    @posts.delete_if{
      |p| !User.find(p.user_id).befriended?(current_user) && p.user_id != current_user.id
    }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    if !User.find(@post.user_id).befriended?(current_user) && @post.user_id != current_user.id
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'This post is not visible to you.' }
      end
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @post }
      end
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <!--<%= f.label :content %><br />-->
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li>
	<p class="content"><%= post.content %></p>
	<% if !post.image.blank? %>
        <%= image_tag post.image.url(:original) %>
    <% end %>
	<span class="timestamp">Posted <%= post.created_at %></span>
</li>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Timeline</h1>

<div class="postsTimeline">
    <% @posts.each do |post| %>
    <div class="postWrapper">
        <div class="postPicture">
            <% if !post.user.avatar.blank? %>
                <%= image_tag post.user.avatar.url(:thumb) , :alt => "profile picture" %>
            <% else %>
                <%= image_tag "default_profile_picture.png" , :alt => "profile picture" %>
            <% end %>
        </div>
        <div class="postAuthor"><%= link_to post.user.name, user_path(post.user) %></div>
        <div class="postContent">
            <% if !post.image.blank? %>
            <div class="postImage">
                <%= image_tag post.image.url(:original) %>
            </div>
            <% end %>

            <%= post.content %>
        </div>

        <% if(current_user.admin || current_user==post.user) %>
            <span class="postControls"><%= link_to 'Edit', edit_post_path(post)  %>&nbsp;|&nbsp;<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        <% end %>
    </div>
    <% end %>
</div>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Content:</b>
	<%= @post.content %>

  	<% if !@post.image.blank? %>
		<%= image_tag @post.image.url(:original) %>
	<% end %>
</p>

<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>